services:
  backend:
    build:
      context: ./backend
      target: builder
    command: sh -c "npm run migration:run && npm run seed && npm run dev"
    environment:
      SEED_DATABASE: true
      NODE_ENV: test
      JWT_SECRET: test-jwt-secret
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:4200
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      MAX_FILE_SIZE: 5242880
      UPLOAD_PATH: ./uploads
      CLEANUP_ENABLED: false
